export type { DashboardRecord } from "./types"
export { DashboardListPage } from "./pages/dashboard-list/dashboard-list"
export { DashboardDetailPage } from "./pages/dashboard-detail/dashboard-detail"
export { DashboardCanvas } from "./pages/dashboard-detail/components/dashboard-canvas"
export { WidgetRenderer } from "./pages/dashboard-detail/components/widget-renderer"
